import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{Home,Inbox,Star,Clock3,Search,Settings,Plus,ShoppingBag,Plane,Receipt,WalletCards,Sun,Moon,Menu,X,Mail,RefreshCw,LogOut,AlertCircle}from'lucide-react';import'./styles.css';import{gmail,StoredAccount}from'./providers/gmail';

type Theme='light'|'dark';
function App(){const[theme,setTheme]=useState<Theme>(()=>(localStorage.getItem('glz-theme')as Theme)||'dark');const[open,setOpen]=useState(false);const[accounts,setAccounts]=useState<StoredAccount[]>(gmail.accounts());const[error,setError]=useState('');const[connecting,setConnecting]=useState(false);useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('glz-theme',theme)},[theme]);useEffect(()=>{gmail.finishOAuth().then(a=>a&&setAccounts(gmail.accounts())).catch(e=>setError(e instanceof Error?e.message:String(e)))},[]);
const connect=async()=>{setError('');setConnecting(true);try{await gmail.connect()}catch(e){setError(e instanceof Error?e.message:String(e));setConnecting(false)}};
return <div className="app"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><div className="brandmark">G</div><div><b>Glz</b><span>Inbox</span></div><button className="mobileClose" onClick={()=>setOpen(false)}><X/></button></div><nav><Nav icon={<Home/>} label="Home" active/><Nav icon={<Inbox/>} label="Inbox"/><Nav icon={<Star/>} label="Priority"/><Nav icon={<Clock3/>} label="Later"/></nav><Section title="Accounts">{accounts.length===0?<div className="sideEmpty">No accounts connected</div>:accounts.map(a=><button className="account" key={a.id}><i style={{background:'#4285f4'}}/><span><b>{a.email}</b><small>Google</small></span></button>)}</Section><Section title="Bundles"><Nav icon={<ShoppingBag/>} label="Purchases"/><Nav icon={<WalletCards/>} label="Finance"/><Nav icon={<Plane/>} label="Travel"/><Nav icon={<Receipt/>} label="Receipts"/></Section><div className="sideBottom"><button className="add" onClick={connect} disabled={connecting}><Plus/> {connecting?'Connecting…':'Add Google account'}</button><Nav icon={<Settings/>} label="Settings"/></div></aside>
<main><header><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><div className="search"><Search/><input placeholder="Search connected mail…" disabled={accounts.length===0}/></div><button className="theme" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun/>:<Moon/>}</button></header><section className="content"><div className="welcome"><div><span className="eyebrow">GLZ INBOX</span><h1>Your communications, in one place.</h1><p>{accounts.length?'Connected accounts are ready for live mail sync.':'Connect an account to begin. Nothing is filled with sample data.'}</p></div></div>{error&&<div className="error"><AlertCircle/>{error}</div>}{accounts.length===0?<ConnectState onConnect={connect} busy={connecting}/>:<Connected accounts={accounts} onDisconnect={(id)=>{gmail.disconnect(id);setAccounts(gmail.accounts())}}/>}</section></main>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}</div>}
function ConnectState({onConnect,busy}:{onConnect:()=>void,busy:boolean}){return <div className="connectState"><div className="connectIcon"><Mail/></div><span className="chip">PHASE 2</span><h2>Connect your first inbox</h2><p>Glz Inbox only displays information retrieved from accounts you connect. Start with Google; additional providers will plug into the same account model.</p><button className="primary" onClick={onConnect} disabled={busy}>{busy?<><RefreshCw className="spin"/>Connecting…</>:<>Connect Google account</>}</button><small>OAuth tokens remain in this browser during this development phase.</small></div>}
function Connected({accounts,onDisconnect}:{accounts:StoredAccount[],onDisconnect:(id:string)=>void}){return <><div className="sectionTitle"><div><h2>Connected accounts</h2><p>Only real connected sources appear here.</p></div></div><div className="accountGrid">{accounts.map(a=><div className="connectedCard" key={a.id}><div className="googleMark">G</div><div><b>{a.email}</b><span>Google · connected</span></div><button title="Disconnect" onClick={()=>onDisconnect(a.id)}><LogOut/></button></div>)}<button className="newAccount" onClick={()=>gmail.connect()}><Plus/><span>Add another Google account</span></button></div><div className="panel emptyPanel"><RefreshCw/><h3>Mail sync is ready to be wired next</h3><p>This space stays empty until Gmail returns actual mailbox data. Glz Inbox will not synthesize messages, counts, recommendations, or activity.</p></div></>}
function Nav({icon,label,active=false}:{icon:React.ReactNode,label:string,active?:boolean}){return <button className={'nav '+(active?'active':'')}>{icon}<span>{label}</span></button>}
function Section({title,children}:{title:string,children:React.ReactNode}){return <section className="sideSection"><label>{title}</label>{children}</section>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);