import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{Home,Inbox,Star,Clock3,Search,Settings,Plus,ShoppingBag,Plane,Receipt,WalletCards,Package,ShieldAlert,MessageSquareReply,Archive,Sun,Moon,Menu,X,ChevronRight,Mail,CheckCircle2}from'lucide-react';import'./styles.css';

type Theme='light'|'dark';
const accounts=[{name:'Personal',provider:'Google',color:'#4285f4',count:12},{name:'Work',provider:'Google',color:'#34a853',count:5},{name:'Outlook',provider:'Microsoft',color:'#0078d4',count:6},{name:'Proton',provider:'Coming later',color:'#6d4aff',count:0}];
const recent=[['Amazon','Your order has shipped','2m','Purchase'],['Microsoft','New sign-in detected','14m','Security'],['Spectrum','Your monthly statement is ready','42m','Bill'],['Daniel Rivera','Re: Weekend plans','1h','Personal']];
function App(){const[theme,setTheme]=useState<Theme>(()=>(localStorage.getItem('glz-theme')as Theme)||'dark');const[open,setOpen]=useState(false);useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('glz-theme',theme)},[theme]);return <div className="app">
<aside className={open?'sidebar open':'sidebar'}><div className="brand"><div className="brandmark">G</div><div><b>Glz</b><span>Inbox</span></div><button className="mobileClose" onClick={()=>setOpen(false)}><X/></button></div>
<nav><Nav icon={<Home/>} label="Home" active/><Nav icon={<Inbox/>} label="Inbox" badge="23"/><Nav icon={<Star/>} label="Priority" badge="5"/><Nav icon={<Clock3/>} label="Later" badge="4"/></nav>
<Section title="Accounts">{accounts.map(a=><button className="account" key={a.name}><i style={{background:a.color}}/><span><b>{a.name}</b><small>{a.provider}</small></span>{a.count>0&&<em>{a.count}</em>}</button>)}</Section>
<Section title="Bundles"><Nav icon={<ShoppingBag/>} label="Purchases"/><Nav icon={<WalletCards/>} label="Finance"/><Nav icon={<Plane/>} label="Travel"/><Nav icon={<Receipt/>} label="Receipts"/></Section>
<div className="sideBottom"><button className="add"><Plus/> Add account</button><Nav icon={<Settings/>} label="Settings"/></div></aside>
<main><header><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><div className="search"><Search/><input placeholder="Search mail or ask Glz Inbox…"/></div><button className="theme" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun/>:<Moon/>}</button><div className="avatar">M</div></header>
<section className="content"><div className="welcome"><div><span className="eyebrow">SUNDAY · SEPTEMBER 28</span><h1>Good evening, Marcos.</h1><p>Here’s what matters across your inboxes.</p></div><div className="status"><i/> All accounts up to date</div></div>
<div className="summary"><Metric n="23" label="Unread" sub="Across 3 accounts"/><Metric n="5" label="Need attention" sub="2 are time-sensitive"/><Metric n="4" label="For later" sub="Next item tomorrow"/><Metric n="3" label="Deliveries" sub="1 arriving tomorrow"/></div>
<div className="grid"><div className="panel attention"><PanelHead title="Needs attention" link="View all"/><Action icon={<MessageSquareReply/>} tone="blue" title="Daniel may be waiting for a reply" text="Last message received yesterday · Personal" primary="Reply" secondary="Later"/><Action icon={<ShieldAlert/>} tone="amber" title="Review a new Microsoft sign-in" text="Security alert · 14 minutes ago" primary="Review" secondary="Dismiss"/><Action icon={<Receipt/>} tone="violet" title="Your Spectrum statement is ready" text="$87.99 · Due October 12" primary="View bill" secondary="Done"/></div>
<div className="panel today"><PanelHead title="Today" link="Open timeline"/><div className="timeline"><Event icon={<Package/>} time="Tomorrow" title="Amazon delivery" text="Arriving by 8 PM"/><Event icon={<WalletCards/>} time="Oct 12" title="Spectrum payment" text="$87.99 due"/><Event icon={<Clock3/>} time="Tomorrow" title="2 snoozed conversations" text="Return to your dashboard"/></div></div></div>
<div className="grid lower"><div className="panel recommendations"><PanelHead title="Recommended for you" link="Why these?"/><div className="recommend"><div className="recommendIcon"><Archive/></div><div><span className="chip">CLEAN UP</span><h3>Clear some old promotions?</h3><p>17 promotional messages are over 30 days old and haven't been opened.</p><div><button>Review 17</button><button className="ghost">Dismiss</button></div></div></div></div>
<div className="panel"><PanelHead title="Recent" link="Open inbox"/>{recent.map((r,i)=><div className="mailrow" key={r[0]}><div className="sender">{r[0][0]}</div><div className="mailtext"><b>{r[0]}</b><span>{r[1]}</span></div><small>{r[3]}</small><time>{r[2]}</time><ChevronRight/></div>)}</div></div>
<footer><CheckCircle2/> Dashboard uses demonstration data for Phase 1</footer></section></main>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}</div>}
function Nav({icon,label,badge,active=false}:{icon:React.ReactNode,label:string,badge?:string,active?:boolean}){return <button className={'nav '+(active?'active':'')}>{icon}<span>{label}</span>{badge&&<em>{badge}</em>}</button>}
function Section({title,children}:{title:string,children:React.ReactNode}){return <section className="sideSection"><label>{title}</label>{children}</section>}
function Metric({n,label,sub}:{n:string,label:string,sub:string}){return <div className="metric"><strong>{n}</strong><div><b>{label}</b><span>{sub}</span></div></div>}
function PanelHead({title,link}:{title:string,link:string}){return <div className="panelHead"><h2>{title}</h2><button>{link}<ChevronRight/></button></div>}
function Action({icon,tone,title,text,primary,secondary}:{icon:React.ReactNode,tone:string,title:string,text:string,primary:string,secondary:string}){return <div className="action"><div className={'actionIcon '+tone}>{icon}</div><div><b>{title}</b><span>{text}</span></div><div className="actionBtns"><button>{primary}</button><button className="ghost">{secondary}</button></div></div>}
function Event({icon,time,title,text}:{icon:React.ReactNode,time:string,title:string,text:string}){return <div className="event"><div className="eventIcon">{icon}</div><div><small>{time}</small><b>{title}</b><span>{text}</span></div></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);